/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author Hp
 */
public class Calculator extends javax.swing.JFrame {
    int i = 0, q;
    double inputs[] = new double[5] ;
    double subresult, result ;
    boolean dotFlag = true ;
    String operation[] = new String[5] ;
     
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        btnDot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnPlus.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnMultiply.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btnMultiply.setText("*");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btnMinus.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btnC.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnEqual.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnDivide.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btnDot.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        btnDot.setText(".");
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField)
                        .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnEqual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn4)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btn8)
                    .addComponent(btn7)
                    .addComponent(btn9)
                    .addComponent(btnMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0)
                    .addComponent(btnDivide)
                    .addComponent(btnDot)
                    .addComponent(btnC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEqual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String str = jTextField.getText() + btn7.getText() ;
        jTextField.setText(str);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String str = jTextField.getText() + btn1.getText();
        jTextField.setText(str);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String str = jTextField.getText() + btn2.getText(); 
        jTextField.setText(str);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String str = jTextField.getText() + btn3.getText();
        jTextField.setText(str);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String str = jTextField.getText() + btn4.getText();
        jTextField.setText(str);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String str = jTextField.getText() + btn5.getText();
        jTextField.setText(str);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        String str = jTextField.getText() + btn6.getText();
        jTextField.setText(str);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String str = jTextField.getText() + btn8.getText();
        jTextField.setText(str);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        String str = jTextField.getText() + btn9.getText();
        jTextField.setText(str);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        String str = jTextField.getText() + btn0.getText();
        jTextField.setText(str);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        jTextField.setText("");
        jLabel.setText("");
        i = 0 ; result = 0 ;
        
        btnPlus.setEnabled(true);
        btnMinus.setEnabled(true);
        btnMultiply.setEnabled(true);
        btnDivide.setEnabled(true);
    }//GEN-LAST:event_btnCActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        if(!jTextField.getText().equals("")){
            dotFlag = true ;
            if( i == 0 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "+");
                i ++ ;           
                operation[i] = "+" ;
                jTextField.setText("");              
            }
            else if( i == 1 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "+");
                i ++ ;
                operation[i] = "+" ;
                jTextField.setText("");

            }
            else if( i == 2 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "+");
                i ++ ;
                operation[i] = "+" ;
                jTextField.setText("");

            }
            else if( i == 3 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "+");
                i ++ ;
                btnPlus.setEnabled(false);
                btnMinus.setEnabled(false);
                btnMultiply.setEnabled(false);
                btnDivide.setEnabled(false);
                operation[i] = "+" ;
                jTextField.setText("");

            }
        }
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        if(!jTextField.getText().equals("")){
            dotFlag = true ;
            if( i == 0 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "-");
                i ++ ;           
                operation[i] = "-" ;
                jTextField.setText("");              
            }
            else if( i == 1 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "-");
                i ++ ;
                operation[i] = "-" ;
                jTextField.setText("");

            }
            else if( i == 2 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "-");
                i ++ ;
                operation[i] = "-" ;
                jTextField.setText("");

            }
            else if( i == 3 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "-");
                i ++ ;
                btnPlus.setEnabled(false);
                btnMinus.setEnabled(false);
                btnMultiply.setEnabled(false);
                btnDivide.setEnabled(false);
                operation[i] = "-" ;
                jTextField.setText("");

            }
        }
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        if(dotFlag){
            String str = jTextField.getText() + btnDot.getText();
            jTextField.setText(str);
            dotFlag = false ;
        }
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        if(!jTextField.getText().equals("")){
            dotFlag = true ;
            if( i == 0 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "*");
                i ++ ;           
                operation[i] = "*" ;
                jTextField.setText("");              
            }
            else if( i == 1 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "*");
                i ++ ;
                operation[i] = "*" ;
                jTextField.setText("");

            }
            else if( i == 2 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "*");
                i ++ ;
                operation[i] = "*" ;
                jTextField.setText("");

            }
            else if( i == 3 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "*");
                i ++ ;
                btnPlus.setEnabled(false);
                btnMinus.setEnabled(false);
                btnMultiply.setEnabled(false);
                btnDivide.setEnabled(false);
                operation[i] = "*" ;
                jTextField.setText("");

            }
        }
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        if(!jTextField.getText().equals("")){
            dotFlag = true ;
            if( i == 0 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "/");
                i ++ ;           
                operation[i] = "/" ;
                jTextField.setText("");              
            }
            else if( i == 1 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "/");
                i ++ ;
                operation[i] = "/" ;
                jTextField.setText("");

            }
            else if( i == 2 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "/");
                i ++ ;
                operation[i] = "/" ;
                jTextField.setText("");

            }
            else if( i == 3 ){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "/");
                i ++ ;
                btnPlus.setEnabled(false);
                btnMinus.setEnabled(false);
                btnMultiply.setEnabled(false);
                btnDivide.setEnabled(false);
                operation[i] = "/" ;
                jTextField.setText("");

            }
        }
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        if(!jTextField.getText().equals("")){
            if(i == 1){            
                inputs[i] = Double.parseDouble(jTextField.getText()) ;            
                if(operation[1].equals("+"))
                    result = inputs[0] + inputs[1] ;              
                else if(operation[1].equals("-"))
                    result = inputs[0] - inputs[1] ;
                else if(operation[1].equals("*"))
                    result = inputs[0] * inputs[1] ;
                else if(operation[1].equals("/"))
                    result = inputs[0] / inputs[1] ;

                jTextField.setText("");
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "=" + result + " ");
            }
            else if(i == 2){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                for(q = 0 ; q < i ; q ++){
                    if(operation[q+1].equals("/"))
                        result = inputs[q] / inputs[q+1] ;
                    else if(operation[q+1].equals("*"))
                        result = inputs[q] * inputs[q+1] ;
                    else if(operation[q+1].equals("+"))
                        result = inputs[q] + inputs[q+1] ;
                    else if(operation[q+1].equals("-"))
                        result = inputs[q] - inputs[q+1] ;
                    if((q + 1) != i)
                        inputs[q+1] = result ;
                }
                jTextField.setText("");
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "=" + result + " ");

            }
            else if(i == 3){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                for(q = 0 ; q < i ; q ++){
                    if(operation[q+1].equals("/"))
                        result = inputs[q] / inputs[q+1] ;
                    else if(operation[q+1].equals("*"))
                        result = inputs[q] * inputs[q+1] ;
                    else if(operation[q+1].equals("+"))
                        result = inputs[q] + inputs[q+1] ;
                    else if(operation[q+1].equals("-"))
                        result = inputs[q] - inputs[q+1] ;
                    if((q + 1) != i)
                        inputs[q+1] = result ;
                }
                jTextField.setText("");
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "=" + result + " ");

            }
            else if(i == 4){
                inputs[i] = Double.parseDouble(jTextField.getText()) ;
                for(q = 0 ; q < i ; q ++){
                    if(operation[q+1].equals("/"))
                        result = inputs[q] / inputs[q+1] ;
                    else if(operation[q+1].equals("*"))
                        result = inputs[q] * inputs[q+1] ;
                    else if(operation[q+1].equals("+"))
                        result = inputs[q] + inputs[q+1] ;
                    else if(operation[q+1].equals("-"))
                        result = inputs[q] - inputs[q+1] ;
                    if((q + 1) != i)
                        inputs[q+1] = result ;
                }
                jTextField.setText("");
                jLabel.setText(jLabel.getText() + String.valueOf(inputs[i]) + "=" + result + " ");

            }
            
        }
    }//GEN-LAST:event_btnEqualActionPerformed

    /**
     * @param args the command" line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Calculator calc = new Calculator() ;
                calc.setTitle("Calculator");
                calc.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPlus;
    private javax.swing.JLabel jLabel;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
